baseURL = "https://www.yoranbrondsema.com/"
languageCode = "en-us"
title = "Yoran Brondsema"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-109409655-1"
paginate = 200

[params]
  name = "Yoran Brondsema"
  description = "Blog about passive investing for Belgians and Europeans."
  bio = "Yoran blogs about passive investing for Belgians and Europeans. CTO of Curvo and Sutori."
  enableRSS = true
  enableGoogleAnalytics = true

  # Add custom assets with their paths relative to the static folder
  customCSS = []
  customJS  = []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
  home = ""
  about = ""
  archive = ""
  subscribe = "RSS"
  tags = ""
  # Pagination links
  olderPosts = ""
  newerPosts = ""
  readMore = ""
  copyright = ""
  # Sharing options and author information in posts
  tweet = ""
  share = ""
  # 404 page
  title404 = ""
  subtitle404 = ""

  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""
