baseURL = "https://www.yoranbrondsema.com/"
languageCode = "en-us"
title = "Yoran Brondsema"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-109409655-1"

[params]
  name = "Yoran Brondsema"
  description = "CTO of Sutori"
  bio = "CTO of Sutori"
  enableRSS = true
  enableGoogleAnalytics = true

  enableDisqus = false
  enableDuoshuo = false
  enableGithubIssuesTips = false
  enableBaiduAnalytics = false

  # Add custom assets with their paths relative to the static folder
  customCSS = []
  customJS  = []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
  home = ""
  about = ""
  archive = ""
  subscribe = "RSS"
  tags = ""
  # Pagination links
  olderPosts = ""
  newerPosts = ""
  readMore = ""
  copyright = ""
  # Sharing options and author information in posts
  aboutAuthor = "I am so interesting."
  tweet = ""
  share = ""
  # 404 page
  title404 = ""
  subtitle404 = ""

  # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
  iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""
