[context.production.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"

[[redirects]]
  from = "/about"
  to = "/"
  status = 301

[[redirects]]
  from = "/books"
  to = "/reading"
  status = 301
