[context.production.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"

[[redirects]]
  from = "/about"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/books"
  to = "/reading"
  status = 301
  force = true

[[redirects]]
  from = "/post/taxes-you-should-know-about-as-a-belgian-investor"
  to = "https://curvo.eu/article/taxes-belgian-investors"
  status = 301
  force = true

[[redirects]]
  from = "/post/taxes-you-should-know-about-as-a-belgian-investor/"
  to = "https://curvo.eu/article/taxes-belgian-investors"
  status = 301
  force = true
